workflows:
  ios-build:
    name: Krokersi iOS Build
    instance_type: mac_mini_m1
    environment:
      node: 22
      cocoapods: default
    scripts:
      - name: 1. Instalacja paczek NPM
        script: npm install
      - name: 2. Instalacja wtyczek Apple (CocoaPods)
        script: |
          cd ios/App
          pod install --repo-update
      - name: 3. Budowa aplikacji (Unsigned)
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO
