workflows:
  ios-build:
    name: Krokersi iOS Build
    instance_type: mac_mini_m1
    environment:
      node: 22
    scripts:
      - name: Instalacja i Build
        script: |
          # 1. Instalacja zaleznosci
          npm install
          # 2. Nadanie uprawnien dla wszystkich plikow wykonywalnych w node_modules
          chmod -R +x node_modules/.bin/
          # 3. Dodanie platformy ios
          npx cap add ios || true
          # 4. Synchronizacja
          npx cap sync ios
          # 5. Instalacja Pods (wymuszenie instalacji CocoaPods)
          cd ios/App
          pod install
          # 6. Build
          xcodebuild build -workspace App.xcworkspace -scheme App -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO
