workflows:
  ios-build:
    name: Krokersi iOS Build
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Build iOS (Unsigned)
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO
